import {StyleSheet} from 'react-native';
import theme from '../constants/Theme';

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.surface,
    marginVertical: 6,
    borderRadius: 16,
    padding: 16,
    borderColor: theme.border,
    borderWidth: 1,
  },
  lefContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  midContainer: {
    justifyContent: 'center',
    flex: 1,
    marginLeft: 12,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginRight: 12,
    backgroundColor: theme.background,
    borderWidth: 2,
    borderColor: theme.surface,
    // Add subtle shadow
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  username: {
    fontWeight: '600',
    fontSize: 16,
    color: theme.primary,
    marginBottom: 4,
  },
  lastMessage: {
    fontSize: 14,
    color: theme.textSecondary,
    lineHeight: 20,
  },
  time: {
    fontSize: 12,
    color: theme.textSecondary,
    alignSelf: 'flex-start',
    marginTop: 4,
    fontStyle: 'italic',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: theme.background,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.surface,
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    paddingHorizontal: 8,
    margin: 15,
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    height: 50,
    fontSize: 16,
    color: theme.text,
  },
  searchIcon: {
    margin: 0,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingVertical: 40,
    marginTop: 30,
  },
  emptyText: {
    fontSize: 16,
    textAlign: 'center',
    lineHeight: 24,
    color: theme.textSecondary,
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.primary,
    // Add shadow for lift
    shadowColor: theme.primary,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  chatItemDivider: {
    height: 1,
    backgroundColor: theme.border,
    marginVertical: 8,
    marginHorizontal: 16,
    opacity: 0.7,
  },
  unreadBadge: {
    backgroundColor: theme.primary,
    width: 8,
    height: 8,
    borderRadius: 4,
    position: 'absolute',
    top: 4,
    left: 52,
  },
  badgeContainer: {
    position: 'relative',
  },
  groupAvatar: {
    backgroundColor: theme.secondary + '20',
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4CAF50',
    borderWidth: 2,
    borderColor: theme.surface,
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
});

export default styles;
