import database from '@react-native-firebase/database';

export const MockUsers = async () => {
  const mockUser = {
    mockuser1: {
      name: 'Alice Johnson',
      email: 'alice@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=5',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Software engineer and tech enthusiast.',
      phoneNumber: '+1-555-1010',
    },
    mockuser2: {
      name: 'Bob Smith',
      email: 'bob@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=11',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Loves coding and coffee.',
      phoneNumber: '+1-555-2020',
    },
    mockuser3: {
      name: 'Charlie Brown',
      email: 'charlie@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=3',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Graphic designer with a passion for UX.',
      phoneNumber: '+1-555-3030',
    },
    mockuser4: {
      name: 'Diana Prince',
      email: 'diana@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=9',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Entrepreneur and business consultant.',
      phoneNumber: '+1-555-4040',
    },
    mockuser5: {
      name: 'Edward Stark',
      email: 'edward@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=7',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Cybersecurity expert and ethical hacker.',
      phoneNumber: '+1-555-5050',
    },
    mockuser6: {
      name: 'Fiona Green',
      email: 'fiona@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=13',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Data scientist and AI researcher.',
      phoneNumber: '+1-555-6060',
    },
    mockuser7: {
      name: 'George Wilson',
      email: 'george@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=15',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Full-stack developer and open-source contributor.',
      phoneNumber: '+1-555-7070',
    },
    mockuser8: {
      name: 'Helen Miller',
      email: 'helen@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=23',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Marketing strategist and content creator.',
      phoneNumber: '+1-555-8080',
    },
    mockuser9: {
      name: 'Ian Cooper',
      email: 'ian@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=17',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Blockchain developer and fintech enthusiast.',
      phoneNumber: '+1-555-9090',
    },
    mockuser10: {
      name: 'Julia Davis',
      email: 'julia@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=21',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'UX/UI designer with a love for animation.',
      phoneNumber: '+1-555-1111',
    },
    mockuser11: {
      name: 'Kevin Parker',
      email: 'kevin@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=19',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Tech writer and JavaScript evangelist.',
      phoneNumber: '+1-555-2222',
    },
    mockuser12: {
      name: 'Laura White',
      email: 'laura@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=25',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Cloud engineer and DevOps specialist.',
      phoneNumber: '+1-555-3333',
    },
    mockuser13: {
      name: 'Michael Clark',
      email: 'michael@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=27',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'AI researcher and machine learning expert.',
      phoneNumber: '+1-555-4444',
    },
    mockuser14: {
      name: 'Nancy Adams',
      email: 'nancy@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=29',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Digital marketer with a focus on social media.',
      phoneNumber: '+1-555-5555',
    },
    mockuser15: {
      name: 'Oliver Brown',
      email: 'oliver@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=31',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Backend developer and API architect.',
      phoneNumber: '+1-555-6666',
    },
    mockuser16: {
      name: 'Paula Anderson',
      email: 'paula@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=33',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Project manager with a passion for agile.',
      phoneNumber: '+1-555-7777',
    },
    mockuser17: {
      name: 'Quincy Harris',
      email: 'quincy@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=35',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Cybersecurity analyst and penetration tester.',
      phoneNumber: '+1-555-8888',
    },
    mockuser18: {
      name: 'Rachel Green',
      email: 'rachel@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=37',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Product designer with a focus on user experience.',
      phoneNumber: '+1-555-9999',
    },
    mockuser19: {
      name: 'Samuel Carter',
      email: 'samuel@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=39',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'Mobile app developer and Swift expert.',
      phoneNumber: '+1-555-1212',
    },
    mockuser20: {
      name: 'Tina Blake',
      email: 'tina@example.com',
      imageUrl: 'https://i.pravatar.cc/150?img=41',
      createdAt: database.ServerValue.TIMESTAMP,
      bio: 'AI ethics researcher and speaker.',
      phoneNumber: '+1-555-1313',
    },
  };

  return mockUser;
};
